### ISSUE TITLE
reviewManager doesn't work

### ISSUE THREAD

**Issue by rayastar** [YahiaAngelo/Noted-Android#1]
hey, hi. When I click on Rate app and then dismiss window (without raiting), I can never open rate app view again. What's problem? If you need a video, I can screen it

**Comment by YahiaAngelo** [comment]
The new "In app review" API from google isn't fully stable, i faced many issues with it (sometimes it won't even show at first try).
Guess i will remove it in the next update.

**Comment by rayastar** [comment]
absolutely rught. this api is garbage
